### ISSUE TITLE
setSign doesn't work

### ISSUE THREAD

**Issue by folkertvanheusden** [wensheng/JuicyRaspberryPie#10]
Hi,

Thanks for this excellect plugin!
Had a lot of fun with it already (rss-feed visible high in the sky and lots more).
Now I found that with the latest version, setSign doesn't work: the boards (e.g. oak_sign) stay empty, no text.

**Comment by Tairraos** [comment]
I found this issue and fixed it, see this PR. if the author does not merges it, you can change it by your selves.
https://github.com/wensheng/JuicyRaspberryPie/pull/14

**Comment by folkertvanheusden** [comment]
Thanks!
