### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by slawa19** [wensheng/JuicyRaspberryPie#2]
Please check screenshot. I have latest Java, Python 3.4 
Minecraft 1.9.4
Spygot server 1.9.4 
![minecraft bug](https://cloud.githubusercontent.com/assets/11042798/15274841/2f253b80-1ac5-11e6-91cc-d6c2d7878e12.jpg)

**Comment by RapidR3D** [comment]
Hey slawa19 im having this same problem after i had everything working. It just suddenly started throwing the same console errors as in your screenshot. After 3 days of research i still cant figure it out. Can you please tell me your solution for this problem?

**Comment by sakvaua** [comment]
I'm having the same issue. Connection refused: connect and everything else as slawa19 described

**Comment by wensheng** [comment]
When python tcp server shuts down, the socket is still in wait state, therefore new server can not be started because port is taken.  I added a line that allows reusing port, so it should be working now
