### ISSUE TITLE
Latest commit in 2024, but latest release in 2021

### ISSUE THREAD

**Issue by SimonCoulombe** [wensheng/JuicyRaspberryPie#25]
Hi friends,

Thanks for the hard work adapting the RaspberryJuice.

I was wondering if there is a release file available for the commits you did recently?  Otherwise, what minecraft version should I set before  building the plugin?
thanks

**Comment by Naohiro2g** [comment]
See https://github.com/wensheng/JuicyRaspberryPie/issues/29
