### ISSUE TITLE
python functions with /p in minecraft

### ISSUE THREAD

**Issue by jdawgaz** [wensheng/JuicyRaspberryPie#3]
I am a newbie for minecraft and python. And I have a question.

I notice on your youtube video, that some of the functions in examples.py had default arguments.
I also notice that using JuicyRasperrryPie plugin, that you can list the functions using /p command in minecraft.

I have two questions:
1. Can I pass an argument to a function, essentially overriding the argument that is there? And if so, is it something like /p cube(size=50, typeId=2) ? or something else?
2. can I have multiple python files in the pplugins and will the /p command get all the functions? And if so, does that mean that all functions, (no matter what file they are in), have to be named uniquely?

Thank you.
Jerry

**Comment by wensheng** [comment]
1.  you can "/p cube 10 gold_block" as of today. Bukkit changed api so now it use block name instead of ID.
2. yes, and yes.  I merged a pull-request that provides "update", when you add a new file or new function, do a "/p update", the commands will be available to you.
